name: Docker Build and Deploy
on:
  push:
    branches:
      - TG-17-Mapp-with-import-id

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "::set-output name=lower_repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/8.3/deploy/Dockerfile-Github-Build
          push: true
          tags: ghcr.io/${{ steps.repo_name.outputs.lower_repo }}:latest
